version: '3'
services:
  front:
    build:
      context: .
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./front:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
